<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN S_SerialNumber
 */


class S_SerialNumber_sugar extends Basic {
    public $new_schema = true;
    public $module_dir = 'S_SerialNumber';
    public $object_name = 'S_SerialNumber';
    public $table_name = 's_serialnumber';
    public $importable = true;
    public $team_id;
    public $team_set_id;
    public $acl_team_set_id;
    public $team_count;
    public $team_name;
    public $acl_team_names;
    public $team_link;
    public $team_count_link;
    public $teams;
    public $assigned_user_id;
    public $assigned_user_name;
    public $assigned_user_link;
    public $tag;
    public $tag_link;
    public $id;
    public $name;
    public $date_entered;
    public $date_modified;
    public $modified_user_id;
    public $modified_by_name;
    public $created_by;
    public $created_by_name;
    public $description;
    public $deleted;
    public $created_by_link;
    public $modified_user_link;
    public $activities;
    public $following;
    public $following_link;
    public $my_favorite;
    public $favorite_link;
    public $locked_fields;
    public $locked_fields_link;
    public $a360blueled;
    public $a360dyemotorcurrent;
    public $a360greenled;
    public $a360horizontalimageposition;
    public $a360imagelength;
    public $a360magstartsentinalposition;
    public $a360magzerolength;
    public $a360moduleserial;
    public $a360printheadpower;
    public $a360printheadserial;
    public $a360redled;
    public $a360softwareversion;
    public $a360verticalimageposition;
    public $assemblynumber;
    public $builddate;
    public $coveredinnorthamerica;
    public $currentfirmware;
    public $currentimageend;
    public $currentimagestart;
    public $currentprintheadangle;
    public $currentprintheadassembly;
    public $currentprintheaddensity;
    public $currentprintheadposition;
    public $currentprintheadresistance;
    public $currentprintheadserial;
    public $dateshipped;
    public $dealersoldto;
    public $doublesidedupgradeperformed;
    public $enduro3eucppromotion;
    public $extendedwarranty;
    public $firmware;
    public $helixcurrentfirmware;
    public $helixcurrenthorizontaloffset;
    public $helixcurrentprintheadpower;
    public $helixcurrentprintheadserial;
    public $helixcurrentprintheadtemp;
    public $helixcurrentrollertemp;
    public $helixcurrentverticaloffset;
    public $helixfirmware;
    public $helixhorizontaloffset;
    public $helixprintheadpower;
    public $helixprintheadserial;
    public $helixprintheadtemp;
    public $helixrollertemp;
    public $helixverticaloffset;
    public $imageend;
    public $imagestart;
    public $loanordemoprinterinfo;
    public $loanordemoprinterlentto;
    public $loanshipped;
    public $printernotes;
    public $printheadangle;
    public $printheadassemblyserial;
    public $printheaddensity;
    public $printheadpostion;
    public $printheadresistance;
    public $printheadserial;
    public $recordtype;
    public $registeredon;
    public $reportedstolen;
    public $serialnumber;
    public $serialnumberuid;
    public $soldon;
    public $status;
    public $totalcardsprinted;
    public $uploadedtosalesforce;
    public $voidwarranty;
    public $warrantywarnings;
    
    public function bean_implements($interface){
        switch($interface){
            case 'ACL': return true;
        }
        return false;
    }
    
}