<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN R_RMA
 */


class R_RMA_sugar extends Basic {
    public $new_schema = true;
    public $module_dir = 'R_RMA';
    public $object_name = 'R_RMA';
    public $table_name = 'r_rma';
    public $importable = true;
    public $team_id;
    public $team_set_id;
    public $acl_team_set_id;
    public $team_count;
    public $team_name;
    public $acl_team_names;
    public $team_link;
    public $team_count_link;
    public $teams;
    public $assigned_user_id;
    public $assigned_user_name;
    public $assigned_user_link;
    public $tag;
    public $tag_link;
    public $id;
    public $name;
    public $date_entered;
    public $date_modified;
    public $modified_user_id;
    public $modified_by_name;
    public $created_by;
    public $created_by_name;
    public $description;
    public $deleted;
    public $created_by_link;
    public $modified_user_link;
    public $activities;
    public $following;
    public $following_link;
    public $my_favorite;
    public $favorite_link;
    public $locked_fields;
    public $locked_fields_link;
    public $additionalrepairsnotes;
    public $bookedinby;
    public $bookinginnotes;
    public $cardhopper;
    public $cardstacker;
    public $cleaningroller;
    public $collectionsent;
    public $datereceived;
    public $dateshipped;
    public $despatchref;
    public $dhlcollectioncost;
    public $dyefilm;
    public $exchangeshipped;
    public $filmcassette;
    public $holokotekey;
    public $holokotekeynumber;
    public $itemsbeingreturned;
    public $laminatefilm;
    public $numberofitems;
    public $originalpackaging;
    public $powercable;
    public $powersupply;
    public $prima4hopperbase;
    public $prima4hopperlockinglid;
    public $primaryemail;
    public $quantity;
    public $receivedvia;
    public $recordtype;
    public $retransfercassette;
    public $retransferfilm;
    public $samplecards;
    public $secondaryemail;
    public $serialpartnumber;
    public $shippedvia;
    public $shippingcost;
    public $status;
    public $trackingnumber;
    public $transitdamage;
    public $typeofpart;
    public $usbcable;
    
    public function bean_implements($interface){
        switch($interface){
            case 'ACL': return true;
        }
        return false;
    }
    
}